---
title: "Pull genotype data from T3"
author: Charlotte Brault
output: html_document
date: '`r format(Sys.time(), "%d %B, %Y")`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

# Libraries

```{r load libraries}
suppressPackageStartupMessages(library(here)) # root directory
suppressPackageStartupMessages(library(data.table)) # load data
suppressPackageStartupMessages(library(apercu)) # ap
suppressPackageStartupMessages(library(dplyr)) # formatting
suppressPackageStartupMessages(library(purrr)) # handle lists
## devtools::install_github("chabrault/HRSWGS") # custom package instal
#suppressPackageStartupMessages(library(HRSWGS)) # custom package
## devtools::install_github("TriticeaeToolbox/BrAPI.R")
suppressPackageStartupMessages(library(BrAPI)) # T3 connection
suppressPackageStartupMessages(library(T3BrapiHelpers)) # T3 helper
suppressPackageStartupMessages(library(DT)) # print table
suppressPackageStartupMessages(library(ggplot2)) # plot
suppressPackageStartupMessages(library(vcfR)) # load vcf
suppressPackageStartupMessages(library(progress)) # progress bar

```


# Set up root directory

```{r current dir}
here::i_am("analysis/combine_GRM.Rmd")
source(here("code","useful_functions.R"))
```


```{r}
trials_predictathon <- c("AWY1_DVPWA_2024","TCAP_2025_MANKS","25_Big6_SVREC_SVREC",
                         "OHRWW_2025_SPO","CornellMaster_2025_McGowan","24Crk_AY2-3",
                         "2025_AYT_Aurora","YT_Urb_25","STP1_2025_MCG")
```


# Convert vcf files to GRM matrices

```{r}
tri=trials_predictathon[3]
for(tri in trials_predictathon[2:length(trials_predictathon)]){
  
  write(paste0("Processing trial: ", tri), stdout())
  files <- list.files(here("data","genotypic",tri,"nonFocal"))
  files <- grep(files, pattern=".vcf.gz", value=TRUE)
  files <- grep(files, pattern="_formatted|_imputed", value=TRUE, invert=TRUE)## keep only the unformatted vcf files
  for(file in files){
    
    vcf.p2f <- paste0(here("data","genotypic",tri,"nonFocal"),"/",file)
    
    ## get filename without extension
    file_noext <- gsub(pattern=".vcf.gz","",file)
    p2f.export.vcf <- paste0(here("data","genotypic",tri,"nonFocal"),"/",file_noext,"_formatted.vcf.gz")
    ## use custom function from useful_functions.R
    geno <- format_curate_vcf(vcf.p2f=vcf.p2f,
                              p2f.export.vcf=p2f.export.vcf,
                              remove.chrUkn=FALSE,
                              check.mrk.dups=TRUE,
                              remove.nonPolyMrk=FALSE,
                              tresh.heterozygous=NULL,
                              check.geno.dups=TRUE,
                              thresh.NA.ind=0.5,
                              thresh.NA.mrk=0.5,
                              format.names=FALSE,
                              imputation="Beagle",
                              p2f.beagle=here("code","beagle.27Feb25.75f.jar"),
                              thresh.MAF=0.01,
                              verbose=1)
    
    ## export numeric imputed geno file
    p2f <- paste0(here("data","genotypic",tri,"nonFocal"),"/",file_noext,"_numeric.rds")
    saveRDS(geno, file=p2f)
    
    ## calculate the genomic relationship matrix
    grm <- rrBLUP::A.mat(geno-1)
    ## export grm
    p2f <- paste0(here("data","genotypic",tri,"nonFocal"),"/",file_noext,"_GRM.rds")
    saveRDS(geno, file=p2f)
  }
}
```

# Combine GRM matrices for each program

```{r}
tri=trials_predictathon[8] ## works for 7
for(tri in trials_predictathon){
  
  write(paste0("Processing trial: ", tri), stdout())
  grmList <- list()
  
  ## Step 1: convcert the focal accessions genomic matrix to a GRM
  p2f <- paste0(here("data","genotypic",tri,"clean"),"/",tri,"_genotypes_curated_numeric.rds")
  genoFoc <- readRDS(p2f)
  grmList[[1]] <- rrBLUP::A.mat(genoFoc-1)
  ## Step 2: load the non focal GRM matrices
  files <- list.files(here("data","genotypic",tri,"nonFocal"))
  ## keep only the GRM files
  files <- grep("_GRM.rds", files, value = TRUE)
  grmList <- c(grmList, lapply(files, function(file){
    p2f <- paste0(here("data","genotypic",tri,"nonFocal"),"/",file)
    geno = readRDS(p2f)
    return(rrBLUP::A.mat(geno-1))
  }))
  genoNames <- map(grmList,rownames)
  ap(genoNames)
  ggVennDiagram::ggVennDiagram(genoNames, label_alpha = 0, label_size = 4) 
  
  var_indices <- list()
  for(i in seq_along(grmList)){
    var_indices[[i]] <- match(rownames(grmList[[i]]), unique(unlist(genoNames)))-1
  }
  
  # combine GRM matrices
  comb_grm <- covariance_combiner(
    partial_covs=grmList,
    var_indices=var_indices,
    degrees_freedom=rep(100, length(grmList)),
    calc_sampling_cov = FALSE
  )
  dim(comb_grm$psi)
  grm_combined <- comb_grm$psi
  ## export combined GRM
  p2f <- paste0(here("data","genotypic",tri,"clean"),"/",tri,"_combined_GRM.rds")
  saveRDS(grm_combined, file=p2f)
}
```


